name: "Git Semantic Version"
description: "Determines version of a repo based on git history"
branding:
  icon: "layers"
  color: "blue"
inputs:
  branch:
    description: "The branch name"
    required: true
    default: "master"
  tag_prefix:
    description: "The prefix to use to identify tags"
    required: false
    default: "v"
  major_pattern:
    description: "a string which, if present in a git commit, indicates that a change represents a major (breaking) change"
    required: true
    default: "(MAJOR)"
  minor_pattern:
    description: "a string which, if present in a git commit, indicates that a change represents a minor (feature) change"
    required: true
    default: "(MINOR)"
  main_format:
    description: "Pattern to use when formatting main part of output version"
    required: true
    default: "${major}.${minor}.${patch}"
  increment_format:
    description: "Pattern to use when formatting increment of output version"
    required: true
    default: "{increment}"
  increment_delimiter:
    description: "Pattern to use when formatting the delimiter between the main part and the increment"
    required: true
    default: "dev"
outputs:
  major:
    description: "Current major number"
  minor:
    description: "Current minor number"
  patch:
    description: "Current patch number"
  increment:
    description: "An additional value indicating the number of commits for the current version"
  version:
    description: "The version result, in the format {tag_prefix}{version}{delimiter}{increment}"
  tag:
    description: "The version result, in the format {tag_prefix}{version}{delimiter}{increment}"
runs:
  using: "node12"
  main: "dist/index.js"
