name: "Build"
on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  test:
    name: "Test and Run"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch origin "+refs/tags/*:refs/tags/*"

      - name: NPM Install
        run: npm ci

      - name: Test
        run: npm test

      - name: Package
        run: npm run package

      - name: Run Action
        uses: ./
        id: run
        with:
          branch: ${{ github.ref }}
